leftnav:
- identifier: dab57718-5269-44e8-9f92-ac64b2c469f9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 66870b31-072b-47d4-a316-e3874edd12ed
  name: Calendar
  pageRef: /pages/lab-calendar
  weight: 20
- identifier: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  name: Lab Resources
  pageRef: /pages/lab-resources
  weight: 30
- identifier: 7670d955-bb24-4e23-a65e-42b696c945f7
  name: 'Experiment 1: Genetic Screen'
  pageRef: /pages/experiment-1-genetic-screen
  weight: 40
- identifier: b6a3e37b-39fc-4b65-9180-c825a2012e92
  name: 'Experiment 2: Testing Mutants'
  pageRef: /pages/experiment-2-testing-the-945-factor-resistant-mutants
  weight: 50
- identifier: dfffde89-7e38-4941-8b8d-c59505873b95
  name: Lab Safety Guidelines
  pageRef: /pages/lab-safety-guidelines
  parent: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  weight: 10
- identifier: 4cf9122b-fd70-43dd-ac22-b526d77c36db
  name: Lab Notebook Instructions
  pageRef: /pages/lab-notebook-instructions
  parent: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  weight: 20
- identifier: 8c4dc102-4680-4aab-be07-e144b8cea3dd
  name: Helpful Resources and Links
  pageRef: /pages/external-resources-and-links
  parent: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  weight: 30
- identifier: 6958d9f0-a84c-4524-bcf9-0ec2be792a04
  name: Lab Day 1
  pageRef: /pages/lab-day-1
  parent: 7670d955-bb24-4e23-a65e-42b696c945f7
  weight: 10
- identifier: d6ba9fd8-eae5-4399-8d9a-6a0bb1af4fdb
  name: Lab Day 2
  pageRef: /pages/experiment-1-lab-day-2
  parent: 7670d955-bb24-4e23-a65e-42b696c945f7
  weight: 20
- identifier: f5bf75fd-f7f8-4762-a93b-63714ea58340
  name: Lab Day 3
  pageRef: /pages/experiment-1-lab-day-3
  parent: 7670d955-bb24-4e23-a65e-42b696c945f7
  weight: 30
- identifier: 7b9cb8b5-77c5-44e1-9901-672e967cabdb
  name: Lab Day 4
  pageRef: /pages/experiment-1-lab-day-4
  parent: 7670d955-bb24-4e23-a65e-42b696c945f7
  weight: 40
