leftnav:
- identifier: dab57718-5269-44e8-9f92-ac64b2c469f9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 66870b31-072b-47d4-a316-e3874edd12ed
  name: Calendar
  pageRef: /pages/lab-calendar
  weight: 20
- identifier: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  name: Lab Resources
  pageRef: /pages/lab-resources
  weight: 30
- identifier: dfffde89-7e38-4941-8b8d-c59505873b95
  name: Lab Safety Guidelines
  pageRef: /pages/lab-safety-guidelines
  parent: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  weight: 10
- identifier: 4cf9122b-fd70-43dd-ac22-b526d77c36db
  name: Lab Notebook Instructions
  pageRef: /pages/lab-notebook-instructions
  parent: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  weight: 20
- identifier: 8c4dc102-4680-4aab-be07-e144b8cea3dd
  name: Helpful Resources and Links
  pageRef: /pages/external-resources-and-links
  parent: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  weight: 30
