leftnav:
- identifier: dab57718-5269-44e8-9f92-ac64b2c469f9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 66870b31-072b-47d4-a316-e3874edd12ed
  name: Calendar
  pageRef: /pages/lab-calendar
  weight: 20
- identifier: 335b2c1e-2e1e-43b3-88de-7887c4136ec9
  name: Lab Resources
  pageRef: /pages/lab-resources
  weight: 30
